# Deprecated - Do not use
# This workflow has been replaced by system_test.yml
name: _DEPRECATED_test_kstartup
on:
  workflow_dispatch:
    inputs:
      never_run:
        description: 'This workflow is deprecated'
        required: false
        default: 'deprecated'
jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use System Test instead."
